AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Deployment capstoneproject1

Parameters:
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Select a public subnet from your default VPC.
  
  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select a security group that allows port 80.

Resources:
 
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: CapstoneCluster

  
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: 
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: webapp-container
         
          Image: 541426239397.dkr.ecr.us-east-1.amazonaws.com/capstoneproject1-repo:latest
          PortMappings:
            - ContainerPort: 80

  
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED       
          Subnets: 
            - !Ref SubnetID
          SecurityGroups:
            - !Ref SecurityGroupID
          